language: d
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - software-properties-common
      - libvulkan-dev
      - libvulkan1
      - vulkan-utils

before_script:
  - git clone --branch spirv-1.1-rev1 https://github.com/KhronosGroup/SPIRV-Tools.git ~/spirv-tools
  - git clone https://github.com/KhronosGroup/SPIRV-Headers.git ~/spirv-tools/external/spirv-headers

script: bash -ex .travis-ci.sh
